/**
 * Writes `out/_headers` for Cloudflare Pages from docker/security-headers.conf.
 *
 * The container gets its headers from nginx and the local preview parses the same
 * snippet, so a static host is the third consumer of one source. Writing this file
 * by hand would make it the copy that silently falls behind — the CSP is the app's
 * central claim, and a deployment quietly serving an older one is worse than a
 * deployment serving none, because it still looks correct.
 *
 * Runs as part of `npm run build`, so `out/` is complete no matter who built it.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

/** Reads `add_header Name "value" always;` lines, exactly as preview.mjs does. */
function securityHeaders() {
  const conf = readFileSync(join(ROOT, 'docker', 'security-headers.conf'), 'utf8');
  const headers = {};
  for (const line of conf.split('\n')) {
    const match = line.match(/^\s*add_header\s+(\S+)\s+"([^"]*)"/);
    if (match) headers[match[1]] = match[2];
  }
  return headers;
}

const headers = securityHeaders();
const names = Object.keys(headers);

if (names.length === 0) {
  console.error('No add_header lines found in docker/security-headers.conf — refusing to write an empty _headers.');
  process.exit(1);
}

const body = [
  '# Generated by scripts/generate-headers.mjs from docker/security-headers.conf.',
  '# Do not edit: change the nginx snippet instead, so every deployment target',
  '# keeps sending the same set.',
  '',
  '/*',
  ...names.map((name) => `  ${name}: ${headers[name]}`),
  '',
].join('\n');

const target = join(ROOT, 'out', '_headers');
writeFileSync(target, body, 'utf8');
console.log(`Wrote out/_headers with ${names.length} headers: ${names.join(', ')}`);
